# For more info on HTTP files go to https://aka.ms/vs/httpfile

@hostname=localhost
@port=6006
#@port=8081
@host={{hostname}}:{{port}}
@version=v1
@id=Ticket-01

#GET https://localhost:6006/api/v2/Ticket/

GET https://{{host}}/api/{{version}}/Ticket/

###

GET https://{{host}}/api/{{version}}/Ticket/{{id}}

# ###

GET https://{{host}}/api/{{version}}/Ticket/Ticket-1

# ###

GET https://{{host}}/api/{{version}}/Ticket/SearchQuery?Note=21&currentPage=2&TicketType=Laptop

###

GET https://{{host}}/api/{{version}}/Ticket/Search
Content-Type: application/json
{
  "searchTerm": "",
  "TicketType": "Laptop",
  "Status": "",
  "Note": "21",
  "currentPage": 1,
  "pageSize": 15,
  "orderBy": "CreatedAt"  
}
###

POST https://{{host}}/api/{{version}}/Ticket/
Content-Type: application/json
{
  "id": "Ticket-01",
  "ticketType": "New Laptop",
  "note": "Post http file",        
  "createdBy": "Api"
}

###

# PUT https://{{host}}/api/{{version}}/Ticket/
# Content-Type: application/json
# {
#   "id": "Ticket-01",
#   "createdAt": "2024-08-05T13:03:11.6467073Z",
#   "ticketType": "New Laptop",
#   "note": "N Put 1",        
#   "createdBy": "Api",
#   "modifiedAt": null,
#   "modifiedBy": null,
#   "isDeleted": null,
#   "rowVersion": 925,
#   "email": null
# }

# ###

GET https://{{host}}/api/{{version}}/Ticket/Ticket-1

# ###

PUT https://{{host}}/api/{{version}}/Ticket/
Content-Type: application/json
{
  "id": "Ticket-01",
  "note": "Put 2",        
  "rowVersion": 1198  
}

###

DELETE https://{{host}}/api/{{version}}/Ticket/{{id}}

###

#Seed Data. Only works if count is less Seed/number
POST https://{{host}}/api/{{version}}/Ticket/Seed/21

###