version: '3.4'

services:
  netcorebe.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=6606
      - ASPNETCORE_HTTPS_PORTS=6006
      - DbTypeEnum=PostgreSQL  
      - SeedDb=True
      - ConnectionStrings__DatabasePostgreSQL=Host=netcorebe.db;Port=5432;Database=netcorebe;Username=postgres;Password=postgres; 
    ports:
      - 6606:6606
      - 6006:6006
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro