version: '3.4'

services:
  netcorebe.api:
    image: ${DOCKER_REGISTRY-}netcorebeapi
    container_name: NetCoreBE.Api
    build:
      context: .
      dockerfile: Server/NetCoreBE.Api/Dockerfile
    depends_on:
      - netcorebe.db

  netcorebe.db:
    image: postgres:latest
    container_name: NetCoreBE.Db
    environment:
      - POSTGRES_DB=netcorebe
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      #- DbTypeEnum=PostgreSQL nefunguje, iba override
    # volumes:
    #   - ./.containers/database:/var/lib/postgresql/data
    volumes:
      - ./.containers/database:/var/lib/postgresql/data2
    ports:
      #- 5432:5432
       - 54320:5432

  netcorebe.seq:
    image: datalust/seq:latest
    container_name: NetCoreBE.Seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80

  netcorebe.jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: NetCoreBE.Jaeger
    ports:
      - 4317:4317
      - 4318:4318
      - 16686:16686

  netcorebe.queue:
    image: rabbitmq:management-alpine
    container_name: NetCoreBE.Queue
    hostname: netcorebe-queue
    volumes:
        - ./.containers/queue/data/:/var/lib/rabbitmq
        - ./.containers/queue/log/:/var/log/rabbitmq
    environment:
        RABBITMQ_DEFAULT_USER: guest
        RABBITMQ_DEFAULT_PASS: guest
    ports:
      - 5672:5672
      - 15672:15672

